### ISSUE TITLE
🏳️‍⚧️🏳️‍🌈 Register play451-hates.lgbt.sh

### ISSUE THREAD

**Issue by playstation452** [lgbt-sh/lgbt-sh#120]
### Subdomain Name

play451-hates.lgbt.sh

### DNS Record

gv-h7apg5b3pvczsm.dv.googlehosted.com

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by cvyl** [comment]
Banned for abuse.
