### ISSUE TITLE
Register for a new domain

### ISSUE THREAD

**Issue by HTML2011** [lgbt-sh/lgbt-sh#27]
### Subdomain Name

aiotools.lgbt.sh

### DNS Record

ns1.he.net ; ns2.he.net ; ns3.he.net ; ns4.he.net

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by ly-nld** [comment]
Please do not edit the title of the issue.
