### ISSUE TITLE
roomanet

### ISSUE THREAD

**Issue by dragdropdraw** [lgbt-sh/lgbt-sh#34]
### Subdomain Name

roomanet.lgbt.sh

### DNS Record

65.109.215.156

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by dragdropdraw** [comment]
tanx alot

**Comment by ly-nld** [comment]
Please do not edit the Issue title. Otherwise, it won't work.
